#!/bin/sh
#

CWD=$(pwd)
OUT=/tmp/out/
PKG=/tmp/temporary
TMP=/tmp/lol/$NAME

NAME=glibc
VERSION=2.25

HOST=$ARCH-lsd-linux

mkdir -p $PKG $OUT $TMP

cd $TMP
wget http://ftp.gnu.org/gnu/$NAME/$NAME-$VERSION.tar.xz
tar xvfJ $NAME-$VERSION.tar.xz
rm -rf $NAME-$VERSION.tar.xz
cd $NAME-$VERSION
        export CC="gcc"
        export CXX="g++"
        export BUILDHOST="x86_64-lsd-linux"
        export CFLAGS="-O3 -g2 -mtune=generic -march=x86-64"
	mkdir -v build
	cd       build
	../configure --prefix=/usr                      \
                     --libexecdir=/usr/lib              \
                     --with-headers=/usr/include        \
                     --enable-kernel=2.6.32             \
                     --enable-obsolete-rpc              \
                     --enable-stack-protector=strong    \
                     --enable-add-ons                   \
                     --enable-bind-now                  \
                     --enable-stackguard-randomization  \
                     --enable-lock-elision              \
                     --enable-static-nss                \
                     --without-cvs                      \
                     --without-gd                       \
                     --without-selinux                  \
                     --disable-profile                  \
                     --disable-werror                   \
                     --build=${BUILDHOST}
	make
	make install install_root=$PKG
        make install install_root=$PKG localedata/install-locales
	cp -v ../nscd/nscd.conf $PKG/etc/nscd.conf
	mkdir -pv $PKG/var/cache/nscd
	install -m644 ../posix/gai.conf $PKG/etc/gai.conf
	install -v -Dm644 ../nscd/nscd.tmpfiles $PKG/usr/lib/tmpfiles.d/nscd.conf
	install -v -Dm644 ../nscd/nscd.service $PKG/lib/systemd/system/nscd.service
	rm -v $PKG/usr/sbin/zdump
	mkdir -pv $PKG/usr/lib/locale
	rm -rf $PKG/etc/ld.so.conf
	install -m 0644 $CWD/{hosts,resolv.conf,nsswitch.conf,host.conf,ld.so.conf} $PKG/etc
	mkdir -pv $PKG/etc/ld.so.conf.d
	rm -rf $PKG/usr/bin/tzselect

spackpkg $PKG $OUT/$NAME-$VERSION.spack
rm -rf $TMP $PKG
